#!/usr/bin/env python3
"""Incremental compile manifest helpers.

The compiler manifest is intentionally separate from the human-readable
``manifest.md`` generated by ``regen_meta.py``. It is machine state used by
``kb compile`` to decide whether a raw source must be sent to the LLM.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


COMPILER_VERSION = "2.0"
MANIFEST_REL_PATH = "wiki/_meta/manifest.json"


@dataclass(frozen=True)
class RawSource:
    """A raw source that can be compiled into wiki outputs."""

    key: str
    prompt_path: str
    path: Path
    sha256: str
    layout: str


@dataclass(frozen=True)
class CompilePlan:
    """Preflight result for one compile invocation."""

    sources: list[RawSource]
    changed_sources: list[RawSource]
    manifest: dict[str, dict[str, Any]]
    reasons: dict[str, list[str]]
    compiler_version: str

    @property
    def is_noop(self) -> bool:
        return not self.changed_sources


def utc_now() -> str:
    """Return the manifest timestamp format."""

    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def manifest_path(kb_dir: Path) -> Path:
    return Path(kb_dir) / MANIFEST_REL_PATH


def load_manifest(kb_dir: Path) -> dict[str, dict[str, Any]]:
    path = manifest_path(kb_dir)
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    if not isinstance(data, dict):
        return {}
    manifest: dict[str, dict[str, Any]] = {}
    for key, value in data.items():
        if isinstance(key, str) and isinstance(value, dict):
            manifest[key] = dict(value)
    return manifest


def save_manifest_if_changed(
    kb_dir: Path,
    manifest: dict[str, dict[str, Any]],
) -> bool:
    path = manifest_path(kb_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    text = _manifest_text(manifest)
    try:
        old = path.read_text(encoding="utf-8")
    except OSError:
        old = None
    if old == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def discover_raw_sources(kb_dir: Path) -> list[RawSource]:
    raw_dir = Path(kb_dir) / "raw"
    if not raw_dir.is_dir():
        return []

    sources: list[RawSource] = []
    for item in sorted(raw_dir.iterdir(), key=lambda p: p.name):
        if item.is_dir() and (item / "clean.md").is_file():
            key = f"raw/{item.name}/"
            sources.append(
                RawSource(
                    key=key,
                    prompt_path=f"raw/{item.name}/clean.md",
                    path=item,
                    sha256=_hash_v2_source(item),
                    layout="v2",
                )
            )
        elif item.is_file() and item.suffix == ".md":
            key = f"raw/{item.name}"
            sources.append(
                RawSource(
                    key=key,
                    prompt_path=key,
                    path=item,
                    sha256=_hash_file(item),
                    layout="legacy",
                )
            )
    return sources


def plan_compile(
    kb_dir: Path,
    *,
    compiler_version: str | None = None,
) -> CompilePlan:
    version = compiler_version or COMPILER_VERSION
    manifest = load_manifest(kb_dir)
    sources = discover_raw_sources(kb_dir)

    reasons: dict[str, list[str]] = {}
    changed: list[RawSource] = []
    for source in sources:
        source_reasons = _compile_reasons(
            kb_dir=Path(kb_dir),
            source=source,
            entry=manifest.get(source.key),
            compiler_version=version,
        )
        if source_reasons:
            reasons[source.key] = source_reasons
            changed.append(source)

    return CompilePlan(
        sources=sources,
        changed_sources=changed,
        manifest=manifest,
        reasons=reasons,
        compiler_version=version,
    )


def scoped_compile_prompt(sources: list[RawSource]) -> str:
    """Build a compile prompt constrained to the changed raw sources."""

    lines = [
        "Compile/update the wiki from the changed raw sources listed below.",
        "",
        "Scope rules:",
        "- Read and process only these raw sources as compile inputs.",
        "- Update each affected source summary, concept article, entity page, "
        "comparison page, index, and metadata as needed.",
        "- Preserve unrelated wiki content unless a cross-link or metadata "
        "update is required by these sources.",
        "- Do not ingest new sources or perform web research.",
        "",
        "Changed raw sources:",
    ]
    for source in sources:
        lines.append(
            f"- {source.key} (compile input: {source.prompt_path}, sha256: {source.sha256})"
        )
    return "\n".join(lines)


def snapshot_wiki_outputs(kb_dir: Path) -> dict[str, str]:
    """Return content hashes for files under wiki/ that can be compiler outputs."""

    wiki_dir = Path(kb_dir) / "wiki"
    if not wiki_dir.is_dir():
        return {}
    snapshot: dict[str, str] = {}
    for fp in sorted((p for p in wiki_dir.rglob("*") if p.is_file()), key=str):
        rel = fp.relative_to(kb_dir).as_posix()
        if rel == MANIFEST_REL_PATH:
            continue
        snapshot[rel] = _hash_file(fp)
    return snapshot


def changed_outputs(before: dict[str, str], after: dict[str, str]) -> list[str]:
    return sorted(path for path, digest in after.items() if before.get(path) != digest)


def build_updated_manifest(
    plan: CompilePlan,
    *,
    compiled_sources: list[RawSource],
    changed_output_paths: list[str],
    compiled_at: str,
) -> dict[str, dict[str, Any]]:
    compiled_keys = {source.key for source in compiled_sources}
    changed_output_set = {p for p in changed_output_paths if p}

    updated: dict[str, dict[str, Any]] = {}
    for source in plan.sources:
        prior = _normalise_entry(plan.manifest.get(source.key))
        if source.key in compiled_keys:
            outputs = sorted(set(prior["outputs"]) | changed_output_set)
            updated[source.key] = {
                "sha256": source.sha256,
                "last_compiled": compiled_at,
                "compiler_version": plan.compiler_version,
                "outputs": outputs,
            }
        elif prior["sha256"]:
            updated[source.key] = prior

    return updated


def build_current_manifest(plan: CompilePlan) -> dict[str, dict[str, Any]]:
    """Return a manifest containing only currently present raw sources."""

    current: dict[str, dict[str, Any]] = {}
    for source in plan.sources:
        prior = _normalise_entry(plan.manifest.get(source.key))
        if prior["sha256"]:
            current[source.key] = prior
    return current


def describe_plan(plan: CompilePlan) -> dict[str, Any]:
    return {
        "manifest": MANIFEST_REL_PATH,
        "compiler_version": plan.compiler_version,
        "raw_sources": len(plan.sources),
        "changed_sources": [source.key for source in plan.changed_sources],
        "reasons": plan.reasons,
    }


def _compile_reasons(
    *,
    kb_dir: Path,
    source: RawSource,
    entry: Any,
    compiler_version: str,
) -> list[str]:
    if not isinstance(entry, dict):
        return ["missing-manifest-entry"]

    reasons: list[str] = []
    for field in ("sha256", "last_compiled", "compiler_version", "outputs"):
        if field not in entry:
            reasons.append(f"missing-field:{field}")

    if entry.get("sha256") != source.sha256:
        reasons.append("sha256-changed")
    if entry.get("compiler_version") != compiler_version:
        reasons.append("compiler-version-changed")

    outputs = entry.get("outputs")
    if not isinstance(outputs, list):
        reasons.append("invalid-outputs")
        outputs = []

    for output in outputs:
        if not isinstance(output, str) or not output:
            reasons.append("invalid-output-path")
            continue
        if Path(output).is_absolute():
            reasons.append(f"absolute-output-path:{output}")
            continue
        if not (kb_dir / output).exists():
            reasons.append(f"missing-output:{output}")

    return reasons


def _normalise_entry(entry: Any) -> dict[str, Any]:
    if not isinstance(entry, dict):
        entry = {}
    outputs = entry.get("outputs")
    if not isinstance(outputs, list):
        outputs = []
    return {
        "sha256": entry.get("sha256") if isinstance(entry.get("sha256"), str) else "",
        "last_compiled": (
            entry.get("last_compiled")
            if isinstance(entry.get("last_compiled"), str)
            else ""
        ),
        "compiler_version": (
            entry.get("compiler_version")
            if isinstance(entry.get("compiler_version"), str)
            else ""
        ),
        "outputs": sorted({p for p in outputs if isinstance(p, str) and p}),
    }


def _manifest_text(manifest: dict[str, dict[str, Any]]) -> str:
    ordered = {key: _normalise_entry(manifest[key]) for key in sorted(manifest)}
    return json.dumps(ordered, indent=2, ensure_ascii=False) + "\n"


def _hash_v2_source(source_dir: Path) -> str:
    components = [(Path("clean.md"), source_dir / "clean.md")]
    components.extend(
        (p.relative_to(source_dir), p) for p in sorted(source_dir.glob("raw.*"))
    )
    return _hash_components(components)


def _hash_components(components: list[tuple[Path, Path]]) -> str:
    h = hashlib.sha256()
    for rel, path in components:
        h.update(rel.as_posix().encode("utf-8"))
        h.update(b"\0")
        with path.open("rb") as f:
            for chunk in iter(lambda: f.read(65536), b""):
                h.update(chunk)
        h.update(b"\0")
    return h.hexdigest()


def _hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()
